# Generated by Django 5.2.1 on 2025-05-30 18:29

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_lessonpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('callout', 2), ('image', 3), ('latex', 4)], block_lookup={0: ('porpoise_blocks.text_blocks.HeadingBlock', (), {}), 1: ('porpoise_blocks.text_blocks.ParagraphBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[]], {'children': [('title', wagtail.blocks.CharBlock(help_text='Optional short heading', required=False)), ('body', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol'])), ('style', wagtail.blocks.ChoiceBlock(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Danger'), ('note', 'Note')], help_text='Visual style'))]}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Wrap your LaTeX in $$...$$ or \\(...\\)'})}),
        ),
    ]
