# Generated by Django 5.2.1 on 2025-05-30 18:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_lessonpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('callout', 2), ('image', 3), ('latex', 4)], block_lookup={0: ('porpoise_blocks.text_blocks.HeadingBlock', (), {}), 1: ('porpoise_blocks.text_blocks.ParagraphBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Wrap your LaTeX in $$...$$ or \\(...\\)'})}),
        ),
    ]
