# Generated by Django 5.2.1 on 2025-05-30 18:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_lessonpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('callout', 5), ('image', 6), ('latex', 7)], block_lookup={0: ('porpoise_blocks.text_blocks.HeadingBlock', (), {}), 1: ('porpoise_blocks.text_blocks.ParagraphBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short heading', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [], 'help_text': 'Visual style'}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('body', 3), ('style', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Wrap your LaTeX in $$...$$ or \\(...\\)'})}),
        ),
    ]
