# Generated by Django 5.2.1 on 2025-06-10 04:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_lessonpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('callout', 5), ('quote', 9), ('code', 15), ('image', 16), ('latex', 17)], block_lookup={0: ('porpoise_blocks.text_blocks.HeadingBlock', (), {}), 1: ('porpoise_blocks.text_blocks.ParagraphBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short heading', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [], 'help_text': 'Visual style'}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('body', 3), ('style', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'The main quoted text.', 'label': 'Quote'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said it (optional).', 'label': 'Attribution', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('highlight', 'Highlighted'), ('bordered', 'Bordered')], 'help_text': 'Visual style of the quote block.', 'label': 'Style', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('quote', 6), ('attribution', 7), ('style', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Plain Text'), ('python', 'Python'), ('bash', 'Bash'), ('json', 'JSON'), ('html', 'HTML'), ('javascript', 'JavaScript')], 'help_text': 'Programming language for syntax highlighting.', 'label': 'Language'}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': 'The source code block.', 'label': 'Code'}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional filename or note.', 'label': 'Caption', 'required': False}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('box', 'Boxed'), ('lined', 'Box + Line Numbers')], 'help_text': 'Visual style of the code block.', 'label': 'Style', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('heading', 10), ('language', 11), ('code', 12), ('caption', 13), ('style', 14)]], {}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 17: ('wagtail.blocks.TextBlock', (), {'help_text': 'Wrap your LaTeX in $$...$$ or \\(...\\)'})}),
        ),
    ]
